name: Test Python 3.8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-py38:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: pip install --pre torch==1.13.0.dev20220620  --extra-index-url https://download.pytorch.org/whl/nightly/cpu/
    - run: make setup
    - run: make test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
